# -*- coding: utf-8 -*-
"""class car.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rylV08b35HsswRJt2expNl3X26DsMgt
"""

class Car:
    def __init__(self, name, fuelRate, velocity):
        self.name = name
        self.fuelRate = max(0, min(fuelRate, 100))
        self.velocity = max(0, min(velocity, 200))
        self.is_running = False

    def run(self, velocity, distance):
        self.velocity = max(0, min(velocity, 200))
        self.is_running = True

        fuel_needed = (distance / 10) * (self.fuelRate * 0.1)
        if fuel_needed <= self.fuelRate:
            self.fuelRate -= fuel_needed
            self.stop(0)
        else:

            possible_distance = (self.fuelRate / (self.fuelRate * 0.1)) * 10
            self.fuelRate = 0
            self.stop(distance - possible_distance)

    def stop(self, remaining_distance):
        self.velocity = 0
        self.is_running = False
        if remaining_distance == 0:
            print("Arrived at destination with fuel left ")
        else:
            print(f"Stopped with remaining, fuel is {self.fuelRate:}")