# -*- coding: utf-8 -*-
"""class Employee .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OywyMaUGACdatSTqs5lPYDhLyBBCyugo
"""

from person import Person

class Employee(Person):
    def __init__(self, name, money, mood, healthRate, id, car, email, salary, distanceToWork):
        super().__init__(name, money, mood, healthRate)
        self.id = id
        self.car = car
        self.email = email
        self.salary = salary
        self.distanceToWork = distanceToWork

    def work(self, hours):
        if hours == 8:
            self.mood = "happy"
        elif hours > 8:
            self.mood = "tired"
        else:
            self.mood = "lazy"

    def drive(self, distance):
        if self.car:
            self.car.run(self.car.velocity, distance)

    def refuel(self, gasAmount=100):
        if self.car:
            self.car.fuelRate = max(0, min(self.car.fuelRate + gasAmount, 100))

    def send_mail(self):
        print(f"Email sent from {self.email}")