# -*- coding: utf-8 -*-
"""class person.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJbTRu6Xv5mMxLrTf1Sj7q2f0wy3A8wk
"""

class Person:
    def __init__(self, name, money, mood, healthRate):
        self.name = name
        self.money = money
        self.mood = mood
        self.healthRate = healthRate

    def sleep(self, hours):
        if hours == 7:
            self.mood = "happy"
        elif hours < 7:
            self.mood = "tired"
        else:
            self.mood = "lazy"

    def eat(self, meals):
        if meals == 3:
            self.healthRate = 100
        elif meals == 2:
            self.healthRate = 75
        else:
            self.healthRate = 50

    def buy(self, items):
        self.money -= items * 10