# -*- coding: utf-8 -*-
"""main class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PreBUiW4rQ6MtQV9vYifRia1WaMeuD7W
"""

from class_employee_ import Employee
from class_car import Car
from class_office import Office
import webbrowser

def main():

    car = Car("Flat 128", 100, 100)
    samy = Employee("Samy", 1000, "happy", 100, 1, car, "samy@iti.gov.eg", 5000, 20)
    office = Office("ITI Smart Village", [samy])


    #samy.sleep(7)         happy



    # Print
    print("Employee Details:")
    print(f"Name: {samy.name}")
    print(f"Mood: {samy.mood}")
    print(f"Health: {samy.healthRate}")
    print(f"Salary: {samy.salary}")
    print(f"Car Fuel: {samy.car.fuelRate}")
    print(f"Employees in Office: {Office.employeesNum}")

    # Website opener (select first website deterministically)
    websites = ["https://www.python.org", "https://www.iti.gov.eg", "https://www.google.com"]
    chosen_website = websites[0]
    print(f"Opening website: {chosen_website}")
    webbrowser.open(chosen_website)


if __name__ == "__main__":
    main()